### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by ryskin** [LuanRoger/electron-shadcn#45]
I cloned, installed package, npm run start and it stuck on Running generateAssets hook, I see icon show of app but window is not opening.

**Comment by LuanRoger** [comment]
Hello.

I've tried to reproduce the problem but everything seems to works just fine. The dependencies was updated since the issue was open, including Electron to v`32.0.1`, can you please check if the problem persists?

I think that's a Electron related issue, in that case, is more appropriate to open an issue in the [Electron's repository](https://github.com/electron/electron).

Also, the CI pipeline tests the final executable on Windows, created with the `npm run package` command. If there's something wrong with the build, the test will failed.

**Comment by marcelino-borges** [comment]
Working fine here as well!
What Node version are you using @ryskin?
I have Node 20 here

Great job, btw @LuanRoger !

**Comment by LuanRoger** [comment]
Since this problem is not related to `electron-shadcn` and any additional information was provided, the issue will be closed.
